### ISSUE TITLE
Loop stops displaying any pokemon after 10-15 minutes

### ISSUE THREAD

**Issue by endeavor7** [jxmorris12/PokemonGo-Finder#11]
GitHub issues are for bug reporting and feature requests.  
For general support, join [our discord server](https://discord.gg/Kzp4yky).
To make bug reports easy to find and organized, we close issues that are deemed
out of scope for GitHub Issues and point people to Discord.

Please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.
### Environment info

Operating System:
Windows 7
Installed version of Python:
2.7
### Steps to reproduce
1. Run main.py
2. Wait 10-15 minutes
   3.
### What have you tried?
1. 
### Logs or other output that would be helpful

(If logs are large, please upload as attachment).
Issues with code from which this was originally forked from: 
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/1003

Has been corrected on the develop branch, but not rolled into this fork.

**Comment by HMPoweredMan** [comment]
Also having this issue.

**Comment by everix1992** [comment]
I think this issue was fixed upstream in the PokemonGo-Map repository. When I get home from work, I'm gonna try and rebase this repository on top of that and see if I can't get a working build out that fixes this (if it hasn't already been fixed by then).

**Comment by padenshorey** [comment]
@everix1992 that would be awesome! can you comment back here if you get it working?

**Comment by everix1992** [comment]
@padenshorey Will do!

**Comment by JMieczkowski** [comment]
@everix1992 This issue has been resolved in the dev branch of PokemonGo-Map. They've made some huge changes on how it works.

**Comment by jxmorris12** [comment]
merged with upstream and this should be fixed!

**Comment by endeavor7** [comment]
@jxmorris12 the "master" branch of upstream is no longer being supported, and it still contains the bug which causes updating to fail after an amount of time.  a new fork of the "develop" branch would need to have the pushbullet functionality integrated to correct this issue.
