### ISSUE TITLE
Loop stopping data collection issue persists.

### ISSUE THREAD

**Issue by HMPoweredMan** [jxmorris12/PokemonGo-Finder#16]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used:
- Environment name and version (e.g. Python 2.7):
- Operating System and version (desktop or mobile):

**Comment by padenshorey** [comment]
Yep I just tested again and after about 20 minutes, Pokemon were no longer being received from the server.

**Comment by renzy** [comment]
yeah, i think the access token expires. im messing around with it right now to try and trigger the login again, but i think theres a better way to do this.

**Comment by renzy** [comment]
try changing the get_token function in main.py from....

```
if global_token is None:
    if service == 'ptc':
        global_token = login_ptc(username, password)
    else:
        global_token = login_google(username, password)
    return global_token
else:
    return global_token
```

to just...

```
if service == 'ptc':
    global_token = login_ptc(username, password)
else:
    global_token = login_google(username, password)
return global_token
```

been running for about a half hour although there is probably a better solution

**Comment by xcheneric** [comment]
Just to be sure I'd say if you're good after an hour or two then it's
fixed. What's your step distance at?

**Comment by renzy** [comment]
jk i dont think that worked.

**Comment by renzy** [comment]
@xcheneric i have it at 5. it looks like in the process_step function its hitting the except AttributeError and  breaking. someone more skilled in python might be able to figure this out a lot quicker than me hah. but thats what ive got so far

**Comment by HMPoweredMan** [comment]
Personally, there's no point in having notifications if this can't run longer than 30 minutes. 
renzy appears to be correct that it is hitting that attribute error. I replaced the

```
    except AttributeError:
        break
```

with

```
        except AttributeError:
            pass
```

 _and it seems to be working. I'll check back after lunch._

Nevermind: I'm done. The parent repo seems to be way different at this point.

**Comment by renzy** [comment]
@HMPoweredMan nice! i actually just grabbed the example.py source from https://github.com/AHAAAAAAA/PokemonGo-Map and copied the get_args function from this repo and have it running now, can check back in if it works.

on that other repo, the last commit to the example.py file was "fix script failing after 30 min or so problem" so whatever the diffs are between that file and the main.py in this repo are would clear things up too.

**Comment by HMPoweredMan** [comment]
@renzy That works, but you'll have to figure out how to re-add the notification bit to your updated main.py

**Comment by reactortrip** [comment]
There was some changes to the fullmap_template.html from that fix, not sure if it impacts this though.

**Comment by renzy** [comment]
@HMPoweredMan yeah i just imported notifier & added after pokemons[poke.SpawnPointId] in the for loop...

```
if hasattr(pokemons, poke.SpawnPointId)==False:
    notifier.pokemon_found(pokemons[poke.SpawnPointId]) 
```

**Comment by endeavor7** [comment]
if you comment out @memoize from main.py, it starts a new login every time it loops, which seems to solve the problem.

**Comment by renzy** [comment]
@endeavor7 ahhh, thank you. that makes sense

**Comment by jxmorris12** [comment]
Merged new AHAAAAAAAA updates

**Comment by renzy** [comment]
@jxmorris12 good man, thank you!

friend of mine is running this too on a windows box, i think he was having encoding issues within notifier.py. im not sure if this made any difference but right after the reload(sys) should sys.setdefaultencoding('utf8') be sys.setdefaultencoding('utf-8') ..? running fine on my ubuntu boxes, so idk i dont really have a way to test.

**Comment by reactortrip** [comment]
I have the new version working, still stops functioning after 30 minutes.

**Comment by HMPoweredMan** [comment]
It's allegedly fixed in the develope branch of the parent. Something to do with API token expirinf

**Comment by paperc07** [comment]
yeah it still stops after about 30 mins
