### ISSUE TITLE
Pushbullet notifications stopped linking in google maps.

### ISSUE THREAD

**Issue by poormuffin** [jxmorris12/PokemonGo-Finder#17]
## Expected Behavior

Expect the notification to send link + location
## Current Behavior

No longer does that as of last pull, now it sends just the type and a link, the link from push bullet does not work, and of course I have no idea what it is.  You can presently copy the test and put it in a browser however you cannot click on the message.
## Steps to Reproduce (for bugs)

1. get message
   2.click
   3.shows present location instead of type location
   4.
## Your Environment

- Version used:
- Environment name and version (e.g. Python 2.7):
- Operating System and version (desktop or mobile):

**Comment by stckcrsh** [comment]
Yeah mine now does this as well.

It has to do with the most recent pull request to do the push_link instead of the push_note

nevermind i lied i saw that there has been code changes and i pulled them down works fine now

**Comment by malosaa** [comment]
no issue here

**Comment by jxmorris12** [comment]
ok yeah great - new changes should have fixed this
