### ISSUE TITLE
URL shown twice in pushbullet message

### ISSUE THREAD

**Issue by zer0-t** [jxmorris12/PokemonGo-Finder#21]
hi jxmorris12,

In the pushbullet message the gmaps url is shown twice.
And can you also put the location streetname back in the pushbullet messages like you did in a earlier build?

Thanks

**Comment by KarlTrueman** [comment]
You may not want to do it your self but if you look in the notifier.py and edit its fairly easy to understand and change. I fixed the duplicate url code but im using channels for mine so i cant share the code. ill try create a version for you later if nobody else does

**Comment by bobsage123** [comment]
Also when clicking on the link in the notification area it opens google maps but goes nowhere.

**Comment by KarlTrueman** [comment]
The notification not leading anywhere can be fixed on android by going into device settings finding google maps and removing defaults then next time you click the link it will ask what to open it with choose your browser and it will show you the pin.

**Comment by bobsage123** [comment]
Oddly maps was not set as a default for anything for me. I also wiped defaults for my main browser chrome beta. Clicked the notification link again and still opens a maps link to nothing.

**Comment by jxmorris12** [comment]
fixed

**Comment by bobsage123** [comment]
jxmorris12, just the duplicate link or the link leading nowhere in maps as well?
