### ISSUE TITLE
Options for Only, Display Gym, Display PokeStop and Only Lure are being ignored.

### ISSUE THREAD

**Issue by rickhlx** [jxmorris12/PokemonGo-Finder#23]
Edited config.json for options described, after running main.py the map still shows pokemons that I do not want to see. Same for gyms, and pokestops.

**Comment by rickhlx** [comment]
{
  "auth_service": "ptc",
  "username": "xxxx",
  "password": "xxxxxx",
  "step_limit": 10,
  "location": "xxxxxxx",
  "display_pokestop": "True",
  "display_gym": "True",
  "do_not_notify": "None",
  "ignore": "None",
  "onlylure": "False",
  "only": "Mew",
  "notify": "Bulbasaur,Ivysaur,Venusaur,Charmander,Charmeleon,Charizard,Squirtle,Wartortle,Blastoise,Pikachu,Raichu,Sandshrew,Sandslash,Nidorino,Nidoking,Clefairy,Clefable,Vulpix,Ninetales,Parasect,Diglett,Dugtrio,Mankey,Primeape,Growlithe,Arcanine,Abra,Kadabra,Alakazam,Machop,Machoke,Machamp,Geodude,Graveler,Golem,Ponyta,Rapidash,Magnemite,Magneton,Farfetch'd,Doduo,Dodrio,Dewgong,Grimer,Muk,Cloyster,Haunter,Gengar,Onix,Hypno,Voltorb,Electrode,Exeggcute,Exeggutor,Cubone,Marowak,Hitmonlee,Hitmonchan,Lickitung,Weezing,Rhyhorn,Rhydon,Chansey,Tangela,Kangaskhan,Seadra,Seaking,Starmie,Mr.Mime,Scyther,Jynx,Electabuzz,Magmar,Pinsir,Tauros,Gyarados,Lapras,Ditto,Vaporeon,Jolteon,Flareon,Porygon,Omanyte,Omastar,Kabuto,Kabutops,Aerodactyl,Snorlax,Articuno,Zapdos,Moltres,Dratini,Dragonair,Dragonite,Mewtwo,Mew",
  "pushbullet": "xxxxxxxxxxxxxxx",
  "auto_refresh": 0,
  "port": 80,
  "host": "xxxxxxxxx"
}

**Comment by coolius** [comment]
True and False should not be in speech marks

**Comment by rickhlx** [comment]
true and false statements are case sensitive. Should be undercase with no quotes.
