### ISSUE TITLE
Notifications not Working

### ISSUE THREAD

**Issue by padenshorey** [jxmorris12/PokemonGo-Finder#24]
Notifications are no longer being sent as...

`pokemons[poke.SpawnPointId] = pokemon_obj`

needs to be moved after the if statement in main.py

I'm just new to GitHub and not sure how to fix it myself.

**Comment by rickhlx** [comment]
Having same issue

**Comment by Erid** [comment]
The fix worked for me, you should try to do a pull request. Fork this repository, do the change on your branch, go to https://github.com/jxmorris12/PokemonGo-Finder/pulls and there you can create a pull request using your branch.

**Comment by paperc07** [comment]
explain this better, where do I put it I cant get it to work

EDIT: I did this and it's working

```
  if poke.SpawnPointId not in pokemons:
    pokemons[poke.SpawnPointId] = pokemon_obj
    notifier.pokemon_found(pokemon_obj)
```

**Comment by prestia** [comment]
I submitted a [pull request](https://github.com/jxmorris12/PokemonGo-Finder/pull/29) to fix this earlier today.

**Comment by paperc07** [comment]
oh ok thanks, I got it sorted now

**Comment by bobsage123** [comment]
Unfortunately the  below trick doesn't work for me. When I do this the command prompt immediately closes itself. 

>  poke.SpawnPointId not in pokemons:
>     pokemons[poke.SpawnPointId] = pokemon_obj
>     notifier.pokemon_found(pokemon_obj)

**Comment by tivie** [comment]
Python is indentation sensitive

**Comment by bobsage123** [comment]
Just made sure all indents matched up and same thing. 
Does this look okay? http://i.imgur.com/bJf8ETg.png

**Comment by prestia** [comment]
@bobsage123 no need to move the print line into the if statement, but that shouldn't break anything.

Have you been able to receive push notifications from Pushbullet otherwise? Might be worth sending a test just to make sure everything is configured properly.

**Comment by paperc07** [comment]
mine arent working now ,i just click om it and the google map link doesnt work now ,it was just working yesterday

**Comment by bobsage123** [comment]
@prestia I moved the print line below the "#change" and that seems to have resolved the issue. Thanks

**Comment by jxmorris12** [comment]
fixed
