### ISSUE TITLE
Can't install requirements.txt

### ISSUE THREAD

**Issue by dreyershelby** [jxmorris12/PokemonGo-Finder#25]
The error I'm getting is below:
`Ashs-Air:PokemonGo-Finder juniperdreyer$ pip install --upgrade -r requirements.txt`

`Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==2.6.1 (from -r requirements.txt (line 2))
Collecting requests==2.10.0 (from -r requirements.txt (line 3))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting flask-googlemaps==0.2.0 (from -r requirements.txt (line 4))
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 5))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Requirement already up-to-date: flask==0.11.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 7))
Collecting coveralls==1.1 (from -r requirements.txt (line 8))
  Using cached coveralls-1.1-py2.py3-none-any.whl
Requirement already up-to-date: werkzeug==0.11.10 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Collecting pushbullet.py (from -r requirements.txt (line 10))
  Using cached pushbullet.py-0.10.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf==2.6.1->-r requirements.txt (line 2))
  Using cached setuptools-24.3.0-py2.py3-none-any.whl
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 5))
Requirement already up-to-date: click>=2.0 in /usr/local/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already up-to-date: Jinja2>=2.4 in /usr/local/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Requirement already up-to-date: itsdangerous>=0.21 in /usr/local/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 6))
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 7))
Collecting docopt>=0.6.1 (from coveralls==1.1->-r requirements.txt (line 8))
Collecting coverage>=3.6 (from coveralls==1.1->-r requirements.txt (line 8))
  Using cached coverage-4.1-cp27-cp27m-macosx_10_10_x86_64.whl
Collecting websocket-client (from pushbullet.py->-r requirements.txt (line 10))
Collecting python-magic (from pushbullet.py->-r requirements.txt (line 10))
Requirement already up-to-date: MarkupSafe in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 6))
Collecting six (from websocket-client->pushbullet.py->-r requirements.txt (line 10))
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: geopy, setuptools, protobuf, requests, flask-googlemaps, future, s2sphere, pycryptodomex, gpsoauth, docopt, coverage, coveralls, six, websocket-client, python-magic, pushbullet.py`

`````` Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/geopy'```
``````

**Comment by prestia** [comment]
System Integrity Protection is blocking the install. Try this:

`sudo pip install --ignore-installed --upgrade -r requirements.txt`

**Comment by dreyershelby** [comment]
still won't install:

`Ashs-Air:PokemonGo-Finder juniperdreyer$ pip install --ignore-installed --upgrade -r requirements.txt
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==2.6.1 (from -r requirements.txt (line 2))
Collecting requests==2.10.0 (from -r requirements.txt (line 3))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting flask-googlemaps==0.2.0 (from -r requirements.txt (line 4))
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 5))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting flask==0.11.1 (from -r requirements.txt (line 6))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 7))
Collecting coveralls==1.1 (from -r requirements.txt (line 8))
  Using cached coveralls-1.1-py2.py3-none-any.whl
Collecting werkzeug==0.11.10 (from -r requirements.txt (line 9))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting pushbullet.py (from -r requirements.txt (line 10))
  Using cached pushbullet.py-0.10.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf==2.6.1->-r requirements.txt (line 2))
  Using cached setuptools-24.3.0-py2.py3-none-any.whl
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 5))
Collecting click>=2.0 (from flask==0.11.1->-r requirements.txt (line 6))
Collecting Jinja2>=2.4 (from flask==0.11.1->-r requirements.txt (line 6))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from flask==0.11.1->-r requirements.txt (line 6))
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 7))
Collecting docopt>=0.6.1 (from coveralls==1.1->-r requirements.txt (line 8))
Collecting coverage>=3.6 (from coveralls==1.1->-r requirements.txt (line 8))
  Using cached coverage-4.1-cp27-cp27m-macosx_10_10_x86_64.whl
Collecting websocket-client (from pushbullet.py->-r requirements.txt (line 10))
Collecting python-magic (from pushbullet.py->-r requirements.txt (line 10))
Collecting MarkupSafe (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 6))
Collecting six (from websocket-client->pushbullet.py->-r requirements.txt (line 10))
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: geopy, setuptools, protobuf, requests, click, MarkupSafe, Jinja2, werkzeug, itsdangerous, flask, flask-googlemaps, future, s2sphere, pycryptodomex, gpsoauth, docopt, coverage, coveralls, six, websocket-client, python-magic, pushbullet.py`

``` Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/geopy'
```

**Comment by prestia** [comment]
See edit above. Toss a `sudo` in front.

**Comment by dreyershelby** [comment]
worked! thank you
