### ISSUE TITLE
Bug fix for notifier

### ISSUE THREAD

**Issue by traversc** [jxmorris12/PokemonGo-Finder#27]
Starting from line 719:

```
    pokemons[poke.SpawnPointId] = pokemon_obj

    print "Pokemon :", pokemon_obj

    if poke.SpawnPointId not in pokemons:
        notifier.pokemon_found(pokemon_obj)
```

Adding the object to the array needs to come after the if statement, otherwise it will never trigger.

**Comment by paperc07** [comment]
mine is already like yours and it's still not working

**Comment by padenshorey** [comment]
Just put that first line after the other 3 lines and it'll work.

**Comment by paperc07** [comment]
yeah I just did this and its working

```
  if poke.SpawnPointId not in pokemons:
    pokemons[poke.SpawnPointId] = pokemon_obj
    notifier.pokemon_found(pokemon_obj)
```

**Comment by padenshorey** [comment]
Remove the indent on the last line or it'll be part of the if statement (which you don't want).

**Comment by padenshorey** [comment]
Oh my bad, I misread it. That should work fine.

**Comment by paperc07** [comment]
yeah I was going to say its working, now I am just letting it run to make sure its auto updating using my google api key in the credentials.json file

**Comment by malosaa** [comment]
is it fixed ?
