### ISSUE TITLE
iphone notifs not showing up / grep not working with python main.py

### ISSUE THREAD

**Issue by dreyershelby** [jxmorris12/PokemonGo-Finder#35]
this could just be me being stupid but i can't seem to get iphone notifications to show up. ive set up my pushbullet acct on my computer (doesn't show up there either) and my phone but it doesn't work. ive checked my notifications directly on pushbullet but nothing is there.

so, because of my trouble with iphone notifs not showing up and my laziness and unwillingness to look at a slowly moving list of pokemon, I've tried using grep with `python main.py`: `python ./main.py | grep "Charmander\|Bulbasaur\|Squirtle\|Ivysaur\|Charmeleon\|Wartortle\|Venusaur\|Charizard\|Blastoise"` but it gives me an error after awhile saying something about being backed up or something. i'll edit this post with the error soon once it pops up.

**Comment by jochemdu** [comment]
Dus you actually get the API Key from the website and inserted it in the configuratie.json? Then restart the script.

Als please apply This fix https://github.com/jxmorris12/PokemonGo-Finder/issues/27 And Make site you get the indent Right.

**Comment by jxmorris12** [comment]
Yeah as long as you have everything configured correctly with `main.py` and `configjson` then that should work
