### ISSUE TITLE
Still stops working after 30 minutes even after downloading latest version

### ISSUE THREAD

**Issue by bobsage123** [jxmorris12/PokemonGo-Finder#39]
Tried commenting out the @memoize and the other work arounds but it still stops working after about 30 minutes.

**Comment by paperc07** [comment]
yeah I noticed its been having problems again

**Comment by malosaa** [comment]
no problems here , what is the error ?

**Comment by paperc07** [comment]
It seems the auto updating is working again. The location cant be clicked on from the generated link on your phone in pushbullet, gonna have to use the workaround again until it's fixed

**Comment by bobsage123** [comment]
@malosaa There seems to be no error. Just after about ~30 minutes I stop receiving notifications. If I go back to my PC  I still see the "looping: step 1 out of 100, etc" as if everything is working normal. Someone was kind enough to write a batch script to restart the main.py file after about 25 minutes.

**Comment by jxmorris12** [comment]
working on it
