### ISSUE TITLE
Loops ONCE then stops due to error - guessing its a threading issue

### ISSUE THREAD

**Issue by StraightCircle** [jxmorris12/PokemonGo-Finder#42]
Runs fine for one loop cycle (gets to last step of steps). Then error and stops running.

global_token variable is nothing on second loop pass... perhaps something to do with not finding original thread?

Last few lines of output:

Completed: 100.0%
[-] register_background_thread called
[-] register_background_thread: queueing          <-- stays on this step for 30 seconds
[+] Locale is en
[!] PTC login for: *******\*                                     (username masked)
[-] login_ptc: could not decode JSON from

.....Then there is what appears to be the server reply. (lots of text).....

Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 1073, in run
    self.function(_self.args, *_self.kwargs)
  File "main.py", line 595, in main
    api_endpoint, access_token, profile_response = login(args)
  File "main.py", line 529, in login
    raise Exception('[-] Wrong username/password')
Exception: [-] Wrong username/password

ALSO: not sure if this is relevant but just in case I'll include the output @ start of program...
[-] register_background_thread called
[-] register_background_thread: not running inside Flask so not starting thread
  Restarting with stat
[-] register_background_thread called
[-] register_background_thread: initial registration
[+] Locale is en
[+] Getting initial location

Any ideas / thoughts / suggestions? 

Thanks,
Alex

**Comment by jxmorris12** [comment]
You typed in the wrong username or password, I think

**Comment by StraightCircle** [comment]
The username + password are correct.

It runs for 1 loop OK. fails @ start of second. Same as currently open issue #44

Why is this closed?
