### ISSUE TITLE
expand the search area

### ISSUE THREAD

**Issue by trwk** [jxmorris12/PokemonGo-Finder#50]
Hello, thanks for sharing your code is so great, Is there an option to expand the search area?

**Comment by Silvawar14** [comment]
Have you tried increasing the step count?

**Comment by Silvawar14** [comment]
(Config.json)

{
  "auth_service": "google",
  "username": "myemailuser",
  "password": "pikachu123",
  "step_limit": 5,   **<--Have you tried changing this value?**
  "location": "742 Evergreen Terrace, Arlington, VA",
  "notify": "dratini,magnemite,electabuzz,hitmonchan,hitmonlee,chansey,lapras,snorlax,porygon,mew,mewtwo,moltres,zapdos,articuno,ditto,seel,gyarados,cubone",
  "pushbullet": "o.XyDeiVeYuM5eSv2ssy7AlFGLDl4ajEXj"
}

**Comment by trwk** [comment]
Thanks that work
